const AsyncError = (error) => {
  throw new Error(error);
};

export default AsyncError;
